### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by spmvoss** [st-bender/pyspaceweather#1]
I am using version 0.2.1 with python version 3.10 on Windows. 

I get a `ResourceWarning: unclosed file` warning on line 61 in celestrak.py because the file is not closed. 

Current Code:

```
	for line in open(swpath):
		if line.startswith("UPDATED"):
			# closes the file automatically
			break
	upd = pd.to_datetime(line.lstrip("UPDATED"), utc=True)
	if relative:
		return pd.Timestamp.utcnow() - upd
	return upd
```

Possible Solution:

```
	with open(swpath) as fp: # closes the file automatically
		for line in fp:
			if line.startswith("UPDATED"):
				break
	upd = pd.to_datetime(line.lstrip("UPDATED"), utc=True)
	if relative:
		return pd.Timestamp.utcnow() - upd
	return upd
```

**Comment by st-bender** [comment]
Hi @spmvoss
Thanks for the report.
To my understanding the `for line in ...` should have taken care of closing the file when breaking out of the loop, hence the comment there. But apparently that is not trustworthy enough.
What did you run to get the warning?
Cheers.

**Comment by spmvoss** [comment]
Hi @st-bender 

I haven’t got access to the code I ran right now, I’ll get back to that.

I believe that only the “with” method uses the context manager and closes the file. 

I received the warning when I used the sw_daily() function. Specifically this happened when running it in a unittest class. 

I’ll get back to you with a minimal code snippet

**Comment by st-bender** [comment]
Hi @spmvoss
I think there is no need to dig deeper. I just read that automatic closing with the simple `for line in open()` version depends on the implementations. With your fix this works more reliably.

I'll push a fix soon, again, thanks for the report.
