### ISSUE TITLE
omnie module fails to download dat file on Windows

### ISSUE THREAD

**Issue by watercs** [st-bender/pyspaceweather#2]
On the line 143 in **omni.py**, it is recommended to replace the following line

L143:   _**url = os.path.join(url_base, basename)**

by

**url = url_base + '/' + basename_**

because the path seperator on Windows is ''//". In addition, I notice there may be a problem for the authority of writing files on Windows, but I did not delve into this issue.

Cheers

**Comment by st-bender** [comment]
Hi,

looks like replying by email failed. :(

> On the line 143 in **omni.py**, it is recommended to replace the following line
>
> L143:   _**url = os.path.join(url_base, basename)**
>
> by
>
> **url = url_base + '/' + basename_**
>
> because the path seperator on Windows is ''//". In addition,

Thanks for the report.
I believe it was not a good idea to use `os.path.join()` for URLs.
What made matters worse, was that I used it for the test too, so
it always passed and didn't catch the difference on Windows.

> I notice there may be a problem for the authority of writing files on Windows, but I did not delve into this issue.

Obviously, I don't use Windows, I can only test within CI on GitHub.
Would be nice to know if the approach works on Windows, in principle
the same permissions should be need that were used to install
the package, nothing special, but could you check?
There is also an option to provide a local path for the data files,
let me know if that is an option until I find time for a proper fix.

Cheers.

**Comment by st-bender** [comment]
Hi @watercs 
I pushed a fix (hopefully), could you try if it works now on Windows?

In your environment you can update to the latest GIT version with:

```sh
pip install -U git+https://github.com/st-bender/pyspaceweather/
```

Check that it is the latest development version with

```sh
pip show spaceweather
```
It should print something like

```sh
Name: spaceweather
Version: 0.3.0.dev0
...
```

**Comment by st-bender** [comment]
Unfortunately Github is over-eager in closing issues prematurely.

https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by st-bender** [comment]
Fixed with https://github.com/st-bender/pyspaceweather/commit/f03106fb305540c5632bf0ff4f9fb548886726b0
